# Generated by Django 4.0.5 on 2022-06-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mean_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='size',
            field=models.IntegerField(),
        ),
    ]
