# Generated by Django 4.0.5 on 2022-06-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_cate', models.CharField(choices=[('LI', 'Literature'), ('SP', 'Sports'), ('ED', (('CED', 'Education'), ('AED', 'Adult Education'))), ('MI', 'Miscellaneous')], default='LI', max_length=3)),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
