# Generated by Django 4.0.5 on 2022-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs_app', '0002_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_cate',
            field=models.CharField(choices=[('LI', 'Literature'), ('SP', 'Sports'), ('ED', (('CED', 'Children Education'), ('AED', 'Adult Education'))), ('MI', 'Miscellaneous')], default='LI', max_length=3),
        ),
    ]
